In [3]:
#Week 2: tic-tac-toe with numpy arrays  
import numpy as np
import random

In [4]:
#Exercise 1
import numpy as np

def create_board():
    board = np.zeros((3,3), dtype=int)
    return board

In [5]:
#Exercise 2
def place(board, player, position):
    
    if board[position] == 0:
        board[position] = player
        return board

board = create_board()
place(board, 1, (0, 0))

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
#Exercise 3
def possibilities(board):
    return list(zip(*np.where(board == 0)))

possibilities(board)

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [7]:
#Exercise 4
random.seed(1)

def random_place(board, player):
    
    selections = possibilities(board)
    
    if len(selections) > 0:
        selection = random.choice(selections)
        place(board, player, selection)
        
    return board

random_place(board, 2)

array([[1, 0, 0],
       [2, 0, 0],
       [0, 0, 0]])

In [8]:
#Exercise 5
random.seed(1)
board = create_board()

# write your code here!
for i in range(3):
    random_place(board, 1)
    random_place(board, 2)
    
print(board)

[[2 2 1]
 [0 1 0]
 [0 1 2]]


In [9]:
#Exercise 6
def row_win(board, player):
    
    if np.any(np.all(board==player, axis=1)): # this checks if any row contains all positions equal to player.
        return True
    else:
        return False

row_win(board, 1)

False

In [10]:
#Exercise 7
def col_win(board, player):
    if np.any(np.all(board==player, axis=0)): # this checks if any column contains all positions equal to player
        return True
    else:
        return False

col_win(board, 1)


False

In [19]:
#Exercice 8

def diag_win(board, player):
    
    if np.all(np.diag(board)==player) or np.all(np.diag(np.fliplr(board))==player):
        
        # np.diag returns the diagonal of the array
        # np.fliplr rearranges columns in reverse order
        return True
    else:
        return False

diag_win(board, 2)


False

In [17]:
#Exercise 9
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

evaluate(board)


0

In [22]:
#Exercise 10


#def Play_game():
  #  board = create_board()
  #  possibilities(board)
    
   # winner = 0
   # while winner == 0:
      #  for player in [1,2]: #here I change the positions for [1,2] for each question, 10 and 11.
           # random_place(board, player)
           # winner = evaluate(board)
           # if winner != 0:
                #break


  #  return winner


random.seed(1)

def play_game():
    board = create_board()
    winner = 0
    while winner == 0:
        for player in [1, 2]:
            random_place(board, player)
            winner = evaluate(board)
            if winner != 0:
                break
    return winner

results = [play_game() for i in range(1000)]
results.count(1)


591

In [36]:
# Exercise 11: Play strategy

play_strategic_game()
def play_strategic_game():
    
    board = create_board()
    winner = 0
    board[1, 1] = 1
    
    while winner == 0:
        for player in [2, 1]:
            random_place(board, player)
            winner = evaluate(board)
            if winner != 0:
                break
    return winner 

random.seed(1)
results = [play_strategic_game() for i in range(1000)]
results.count(1)

716